import type { Metadata } from "next";
import { Geist, Geist_Mono, Sansita } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {GeoProvider} from "@/context/GeoContext";
import {Toaster} from "react-hot-toast"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sansita = Sansita({
  variable:"--font-sansita",
  weight:["400","700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <GeoProvider>
    <html
      lang="en"
      className={`${sansita.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <Toaster/>
        {children}</body>
    </html>
    </GeoProvider>
    </ClerkProvider>  
  );
}
